name: Aspire Pharmacy 2
favicon: null
layout_spectrum: 0.29563194676302373
typography_spectrum: 0.30246380902826786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4300378682091832
  lightness: 0.4013882908038795
  saturation: 0.0438176766037941
  rhythmicContrast: 0.9683825336396694
purpose: []
